# Generated by Django 3.0.7 on 2021-04-28 01:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='careerdb',
            fields=[
                ('career_id', models.AutoField(primary_key=True, serialize=False)),
                ('career_department', models.CharField(default='', max_length=200)),
                ('name_of_the_post', models.CharField(default='', max_length=200)),
                ('no_of_vacancies', models.CharField(default='', max_length=200)),
                ('last_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('full_notification', models.FileField(blank=True, null=True, upload_to='career/')),
                ('qualification', models.CharField(default='', max_length=1000)),
                ('application_form', models.FileField(blank=True, null=True, upload_to='career/')),
            ],
        ),
        migrations.CreateModel(
            name='eventsdb',
            fields=[
                ('events_id', models.AutoField(primary_key=True, serialize=False)),
                ('events_title', models.CharField(default='', max_length=200)),
                ('upload', models.FileField(blank=True, null=True, upload_to='events/')),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('location', models.CharField(default='', max_length=200)),
                ('date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='facultydb',
            fields=[
                ('faculty_id', models.AutoField(primary_key=True, serialize=False)),
                ('faculty_name', models.CharField(default='', max_length=200)),
                ('faculty_department', models.CharField(blank=True, max_length=200, null=True)),
                ('faculty_email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('notice_id', models.AutoField(primary_key=True, serialize=False)),
                ('notice_title', models.CharField(default='', max_length=200)),
                ('notice_description', models.CharField(default='', max_length=1000)),
                ('upload', models.FileField(blank=True, null=True, upload_to='notice_board/')),
                ('dateTime', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='resultdb',
            fields=[
                ('result_id', models.AutoField(primary_key=True, serialize=False)),
                ('result_title', models.CharField(default='', max_length=200)),
                ('result_description', models.CharField(blank=True, default='', max_length=1000)),
                ('upload', models.FileField(blank=True, null=True, upload_to='result/')),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='tenderdb',
            fields=[
                ('tender_id', models.AutoField(primary_key=True, serialize=False)),
                ('tender_department', models.CharField(default='', max_length=200)),
                ('tender_name_no', models.CharField(default='', max_length=200)),
                ('tender_contactinfo', models.CharField(default='', max_length=1000)),
                ('opening_date', models.DateTimeField(blank=True, null=True)),
                ('last_date', models.DateTimeField(blank=True, null=True)),
                ('upload', models.FileField(blank=True, null=True, upload_to='tender/')),
            ],
        ),
        migrations.CreateModel(
            name='SuperUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=128)),
                ('email', models.EmailField(max_length=254)),
                ('mobile_no', models.CharField(max_length=13, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=128, null=True)),
                ('mob', models.CharField(blank=True, max_length=10, null=True)),
                ('faculty_contact_info', models.CharField(default='', max_length=200)),
                ('faculty_qualification', models.CharField(default='', max_length=200)),
                ('designation', models.CharField(default='', max_length=200)),
                ('faculty_bio', models.CharField(default='', max_length=2000)),
                ('faculty_pic', models.FileField(blank=True, null=True, upload_to='faculty/resume/')),
                ('faculty', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='my_app.facultydb')),
            ],
            options={
                'verbose_name': 'Resume',
                'verbose_name_plural': 'Resumes',
                'db_table': '',
                'managed': True,
            },
        ),
    ]
