# Generated by Django 3.0.7 on 2021-05-02 03:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notice',
            name='dateTime',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='designation',
        ),
        migrations.AddField(
            model_name='facultydb',
            name='designation',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='notice',
            name='day',
            field=models.CharField(blank=True, default=2, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='notice',
            name='month',
            field=models.CharField(blank=True, default=5, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='notice',
            name='time',
            field=models.CharField(blank=True, default=datetime.time(8, 59, 5, 239484), max_length=200, null=True),
        ),
    ]
