# Generated by Django 3.0.7 on 2021-05-02 03:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_auto_20210502_0859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='month',
            field=models.CharField(blank=True, default='May', max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='notice',
            name='time',
            field=models.CharField(blank=True, default=datetime.time(9, 0, 41, 235070), max_length=200, null=True),
        ),
    ]
