# Generated by Django 3.0.7 on 2021-05-02 07:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_auto_20210502_0900'),
    ]

    operations = [
        migrations.AddField(
            model_name='careerdb',
            name='dt_of_notice',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='careerdb',
            name='last_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notice',
            name='time',
            field=models.CharField(blank=True, default=datetime.time(12, 34, 21, 886975), max_length=200, null=True),
        ),
    ]
