# Generated by Django 3.0.7 on 2021-05-02 07:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_auto_20210502_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventsdb',
            name='day',
            field=models.CharField(blank=True, default=2, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='eventsdb',
            name='month',
            field=models.CharField(blank=True, default='May', max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='eventsdb',
            name='time',
            field=models.CharField(blank=True, default=datetime.time(13, 27, 50, 13900), max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='notice',
            name='time',
            field=models.CharField(blank=True, default=datetime.time(13, 27, 50, 12902), max_length=200, null=True),
        ),
    ]
