# Generated by Django 3.0.7 on 2021-05-02 17:41

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0005_auto_20210502_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventsdb',
            name='time',
            field=models.CharField(blank=True, default=datetime.time(23, 11, 58, 190132), max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='notice',
            name='time',
            field=models.CharField(blank=True, default=datetime.time(23, 11, 58, 189136), max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='hod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept', models.CharField(default='', max_length=1000)),
                ('faculty', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='my_app.facultydb')),
            ],
        ),
    ]
